<!DOCTYPE html>

<html>
    <head>
        <title>BOUTIQUE</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link type="text/css" rel="stylesheet" href="bootstrap/css/bootstrap.min.css"/>
        <link type="text/css" rel="stylesheet" href="bootstrap/css/style.css"/>

        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="bootstrap/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div id="header">
            <nav class="navbar navbar-default">
                <div class=" default-container">
                    
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                       
                      <h2><span class="navbar-brand" style="font-weight: bold;font-size: 50px;height:40px;color : white; margin-right:5px;" >BOUTIQUE</span><img src="images/t1.jpg" title="logo" width="75px" height="75px"/></h2>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                     

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                            <a href="ajout.phtml"><img src="images/b1.jpg" title="ADD" width="50px" height="50px" class=" "/></a>
                            </li>
                         

                              <li>
                               <a href="AfficherTout.phtml"><img src="images/b4.jpg" title="show all" width="50px" height="50px" /></a>
                              </li>

                              </ul>
                       
                    </div><!-- /.navbar-collapse -->
               
                    
                </div><!-- /.container-fluid -->
            </nav>
            
        </div>
    
        <div id="content">
            <div id="slider">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                   
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                    </ol>
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner default-container" role="listbox">
                        <div class="item active">
                            <img src="images/aaaa.jpg" class="img-rounded"  alt="...">
                           
                        </div>
                       <div class="item">
                            <img src="images/d.jpg" class="img-rounded"  alt="...">
                       
                        </div>
                         <div class="item">
                            <img src="images/c2.jpg" class="img-rounded" alt="...">
                            
                        </div>
                       
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div id="services">
                <div class="default-container">
<h8>Bienvenue sur notre site de vente en ligne, sur ce site vous aurez la possibilité d'acheter des accessoires, des vetements ainsi que des chaussures.</h8>
      </div>
</div>


                   <!--  
                    <img src="images/h1.jpg"  class="rounded float-left" alt=""> 
                   <img src="images/h2.jpg" class="img-rounded"  alt="100%x200">
                    <img src="images/h3.jpg" class="img-rounded"  alt="100%x200">
                     <img src="images/c1.jpg" class="img-rounded"  alt="100%x200">
                     <img src="images/c2.jpg" class="img-rounded"  alt="100%x200"> -->
                    
               
                            </div>

                        </div>

                    </div>

                </div>
            </div>
        </div>
        <div id="footer" >
            <div class="default-container" style="padding-top: 60px;">
                <div class="row">
                    <div class="col-md-4">
                        <h4>A propos</h4>
                        <p>
                        <ul>
                            <li>Conditions Générales</li>
                         
                        </ul>  
                        </p>
                    </div>
                    <div class="col-md-4">
                        <h4>Retrouvez nous sur</h4>
                        <p>
                        <ul>
                            <li>twitter</li>
                            <li>Facebook</li>
                            <li>youtube</li>
                        </ul>  
                        </p>
                    </div>                   
                    
                </div>
            </div>
            <div id="copyright">
              <div class="default-container">
                     ***************  Copyright: 2017***************<br> 
                Webddisegn * by sdg * 
        
       
                </div>
            </div>
        </div>
    </body>
</html>
